services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "7524278392:AAGd21uCuExw-JAuko9UC5l9GLrqmwy-mh4"
      - key: WEBHOOK_URL
        value: "https://start-to-messages.onrender.com"
